// Code generated by "stringer -type Type"; DO NOT EDIT.

package scan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[BlankLine-2]
	_ = x[Space-3]
	_ = x[Title-4]
	_ = x[SectionAdornment-5]
	_ = x[Paragraph-6]
	_ = x[Bullet-7]
	_ = x[Comment-8]
	_ = x[HyperlinkStart-9]
	_ = x[HyperlinkPrefix-10]
	_ = x[HyperlinkQuote-11]
	_ = x[HyperlinkName-12]
	_ = x[HyperlinkSuffix-13]
	_ = x[HyperlinkURI-14]
	_ = x[InlineReferenceOpen-15]
	_ = x[InlineReferenceText-16]
	_ = x[InlineReferenceClose-17]
}

const _Type_name = "EOFErrorBlankLineSpaceTitleSectionAdornmentParagraphBulletCommentHyperlinkStartHyperlinkPrefixHyperlinkQuoteHyperlinkNameHyperlinkSuffixHyperlinkURIInlineReferenceOpenInlineReferenceTextInlineReferenceClose"

var _Type_index = [...]uint8{0, 3, 8, 17, 22, 27, 43, 52, 58, 65, 79, 94, 108, 121, 136, 148, 167, 186, 206}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
